### PR TITLE
Log errors returned by recvICMP

### PR DESCRIPTION
**Pull request by CHTJonas**
Currently we throw errors from the `pinger.recvICMP` function away which is very much non-ideal. While having a library print logs to the stdout is also far from ideal, it's arguably a less evil than not reporting them _at all_ at least until such a time that we can implement a proper error-returning or logging interface (#16).

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by mem — APPROVED** [review]

**Comment by SuperQ** [comment]
The other way we could handle this is to use an [errgroup](https://pkg.go.dev/golang.org/x/sync/errgroup) instead of a simple waitgroup.

**Comment by CHTJonas** [comment]
Rebased on top of the logger changes.

**Review by mem — APPROVED** [review]

**Comment by CHTJonas** [comment]
Ping @sparrc for a review please! 🥺

**Comment by CHTJonas** [comment]
Superseded by ff8be3320020b96856d3d48505bcf8926809752e.

**Pull request closed without merging**
