### PR TITLE
Use a guaranteed invalid hostname in TestNewPingerInvalid

### PR DESCRIPTION
**Pull request by rrcollier**
Cleaned up replacement PR for request #104.

### CODE REVIEW

**Comment by CHTJonas** [comment]
Not quite sure what's going on here and why you want to change this. The suite seems to run and pass every test, both locally for me and in our CI environment.

Does `wtf` resolve as a hostname on your network or something?! 😆

**Comment by rrcollier** [comment]
Ah, yes, I turns out there is a 'wtf' in one of my dns search paths. I have now updated my branch to use a guaranteed not to exists fqdn.

**Review by CHTJonas — APPROVED** [review]
Thanks, LGTM! 👍

**Review by sparrc — APPROVED** [review]
LOL! lgtm

**Pull request merged**
