### PR TITLE
Add option not to store all received rtts.

### PR DESCRIPTION
**Pull request by rrcollier**
This prevents memory bloat from a process that wants to do very long running ping tests.

This was previously included by accident in PR 104.

### CODE REVIEW

**Comment by SuperQ** [comment]
This will default to off, which will make the `Statistics()` function not work by default because of the way it uses the `rtts` slice.

This should probably be enabled in the `New()` method.

**Comment by rrcollier** [comment]
Fixed. Thanks for spotting that.

**Review by SuperQ — APPROVED** [review]
LGTM.

**Review by CHTJonas — APPROVED** [review]
🚀

**Pull request merged**
