### PR TITLE
Add ability to set TTL

### PR DESCRIPTION
**Pull request by hamptonmoore**
Recently I needed the ability to set the Ping TTL for a project and couldn't find a package that would let me to do that so I modified this to let me. This is probably useful to other people aswell so I figure why not make a PR. Could probably do with a little bit of reformating how the TTL is sent from the Pinger to the icmpConn.

### CODE REVIEW

**Comment by hamptonmoore** [comment]
Hey, is anything gonna happen with this?

**Comment by CHTJonas** [comment]
[ENOTUITS](https://en.wiktionary.org/wiki/ENOTUITS). Haven't forgotten but just very busy IRL at the moment!

**Comment by CHTJonas** [comment]
Hi @hamptonmoore, we've recently merged into `master`. Please could you rebase this?

**Comment by SuperQ** [comment]
This needs a rebase now that #177 is merged.

**Pull request closed without merging**
