### PR TITLE
TLD 'wtf' now exists, use 'wtfh' instead in TestNewPingerInvalid

### PR DESCRIPTION
**Pull request by rrcollier**

### CODE REVIEW

**Comment by SuperQ** [comment]
This includes some unrelated commits. It looks like you're making commits to your fork master branch.

I recommend ["Fork and Branch"](https://gist.github.com/Chaser324/ce0505fbed06b947d962) workflow to avoid these issues.

**Comment by CHTJonas** [comment]
Poke @rrcollier - could you please remove the unrelated changes and squash this PR into a single commit? Thanks!

**Comment by rrcollier** [comment]
Apologies. I'll tidy this up.

**Comment by CHTJonas** [comment]
Look like I managed to mis-read the code in this PR last night! Typically, we prefer a PR to address a single new feature/bug/enhancement rather than multiple things at once. Could possibly resubmit this as two PRs?

1. Add the opt-out for appending to the slice of rtts.
2. Add the `OnSend` event handler.

**Comment by rrcollier** [comment]
Absolutely. My intention was to send you 3 separate self contained patches/prs. One for the tests. On for on-send handler and I've for the opt out.

However this is my first time contributing more then a trivial typo/documentation fix with git/github, and I also have very little free time right now.

Hope to resubmit this correctly in the next week.

**Comment by rrcollier** [comment]
This is now spilt up into requests 113, 114 & 115.

**Comment by CHTJonas** [comment]
Nice one - thanks! 😄

**Pull request closed without merging**
