### PR TITLE
Don't fragment

### PR DESCRIPTION
**Pull request by mem**
This PR adds a "don't fragment" option that sets the IPv4 don't fragment flag so that ping fails if the packet exceeds the MTU for the link.

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by CHTJonas — CHANGES_REQUESTED** [review]
Looks like both privileged and unprivileged pinging is broken on macOS when I set `pinger.SetDontFragment(true)`.

**Comment by SuperQ** [comment]
This needs a rebase now that #177 is merged.

**Comment by SuperQ** [comment]
Ping, please rebase.

**Comment by Cougar** [comment]
Any progress with that? Is that macOS issue the showstopper right now?

**Comment by SuperQ** [comment]
See https://github.com/go-ping/ping/pull/226

**Pull request closed without merging**
